name: app_glucometro
description: "Aplicacion para el monitoreo de glucosa sin dolor"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_database: ^11.3.5
  firebase_auth: ^5.5.3

  flutter_reactive_ble: ^5.0.3
  permission_handler: ^12.0.0+1

  logger: ^2.0.1

  flutter_svg: ^2.0.7
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo2.png"
  adaptive_icon_background: "#FFFFFF"  # Color de fondo similar al de tu app
  adaptive_icon_foreground: "assets/imgs/logo2.png"  # Si tienes una versión recortada
  remove_alpha_ios: true  # Recomendado para iOS



flutter:

  uses-material-design: true

  assets:
    - assets/imgs/
  
  fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700
  
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
