// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidOptions = FirebaseOptions(
    apiKey: 'AIzaSyCoEPrDrfKHWF-QOlnkdGXXb7aIVqfD0lc',
    appId: '1:254115885542:android:8ce98dc47f90c8f27f2627',
    messagingSenderId: '254115885542',
    projectId: 'glucometro-app',
    databaseURL: 'https://glucometro-app-default-rtdb.firebaseio.com',
    storageBucket: 'glucometro-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpcCTsoqvOWwxo3W-X3fbyaB9drBRSlgA',
    appId: '1:254115885542:web:a4dcdda6c34b18407f2627',
    messagingSenderId: '254115885542',
    projectId: 'glucometro-app',
    authDomain: 'glucometro-app.firebaseapp.com',
    storageBucket: 'glucometro-app.firebasestorage.app',
    measurementId: 'G-GP5Z44P3W7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQhqqXEizbrZmlqhCgK_1qYnlWUuDb1k',
    appId: '1:254115885542:ios:b1b3c77463e27f517f2627',
    messagingSenderId: '254115885542',
    projectId: 'glucometro-app',
    storageBucket: 'glucometro-app.firebasestorage.app',
    iosBundleId: 'com.example.appGlucometro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpcCTsoqvOWwxo3W-X3fbyaB9drBRSlgA',
    appId: '1:254115885542:web:f53a11a63f268c947f2627',
    messagingSenderId: '254115885542',
    projectId: 'glucometro-app',
    authDomain: 'glucometro-app.firebaseapp.com',
    storageBucket: 'glucometro-app.firebasestorage.app',
    measurementId: 'G-3WBX1HV6PX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQhqqXEizbrZmlqhCgK_1qYnlWUuDb1k',
    appId: '1:254115885542:ios:b1b3c77463e27f517f2627',
    messagingSenderId: '254115885542',
    projectId: 'glucometro-app',
    databaseURL: 'https://glucometro-app-default-rtdb.firebaseio.com',
    storageBucket: 'glucometro-app.firebasestorage.app',
    iosBundleId: 'com.example.appGlucometro',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoEPrDrfKHWF-QOlnkdGXXb7a1VqfD0lc',
    appId: '1:254115885542:android:8ce98dc47f90c8f27f2627',
    messagingSenderId: '254115885542',
    projectId: 'glucometro-app',
    databaseURL: 'https://glucometro-app-default-rtdb.firebaseio.com',
    storageBucket: 'glucometro-app.firebasestorage.app',
  );

}